<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('header'); ?>


<header>

</header>

<body>

<div class="col-md-6 col-md-offset-3 col-sm-7 col-sm-offset-2">
    <div class="panel panel-default">
        <div class="panel-body">
            <h3 class="thin text-center">Insert your data to create your account</h3>

            <form action="<?php echo Url::toRoute('user/register')?>" method="post">
                <div class="top-margin">
                    <label>Full Name <span class="text-danger"></span></label>
                    <input type="text" name="fullname" class="form-control">
                </div>
                <div class="top-margin">
                    <label>Username <span class="text-danger"></span></label>
                    <input type="text" name="username" class="form-control">
                </div>
                <div class="top-margin">
                    <label>Email <span class="text-danger"></span></label>
                    <input type="text" name="email" placeholder="email@email.com" class="form-control">
                </div>
                <div class="top-margin">
                    <label>Password <span class="text-danger"></span></label>
                    <input type="password" name="password" class="form-control">
                </div>

                <div class="top-margin">
                    <label>BirthDate <span class="text-danger"></span></label>
                    <input type="text" name="birthdate" class="form-control">
                </div>
                <br>
                <div class="col-lg-7 text-right" >
                    <button class="btn btn-action" type="submit"  background-color="red">REGISTER</button>
                </div>



            </form>
        </div>
    </div>



</body>


<?php Layout::includeLayout('footer')?>