<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('header'); ?>


    <header>

    </header>
<style>

    div.mid {
        position: relative;
        text-align: center;

        border: 3px solid black;
    }
</style>

    <body>

    <div class="col-md-6 col-md-offset-3 col-sm-7 col-sm-offset-2">
        <div class="panel panel-default">
            <div class="panel-body">
                <h3 class="thin text-center">Here below , are the best of the best</h3>
                <BR>


                    <div class="mid">
                        <br>
                            <?php ?>
                        Full Name                          1 - Number one
                        <br>
                        <br>
                        Full Name                          2 - Number two
                        <br>
                        <br>
                        Full Name                          3 - Number three
                        <br>
                        <br>
                        Full Name                          4 - Number four
                        <br>
                        <br>
                        Full Name                          5 - Number five
                        <br>
                        <br>
                        Full Name                          6 - Number six
                        <br>
                        <br>
                        Full Name                          7 - Number seven
                        <br>
                        <br>
                        Full Name                          8 - Number eight
                        <br>
                        <br>
                        Full Name                          9 - Number nine
                        <br>
                        <br>
                        Full Name                          10 - Number ten
                        <br>
                        <br>


                    </div>
                <br>
                <div class="top-margin">


                </div>







            </div>
        </div>



    </body>


<?php Layout::includeLayout('footer')?>