<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\WebObjects\URL;
?>

<!DOCTYPE html>
<?=AssetBundler::css()?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="author"  content="João Santos / Kevin Carvalho">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <title>VIdeo Poker</title>

</head>

<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->

        <div class="navbar-header">

            <a class="navbar-brand" href="<?= Url::toRoute('home/index')?>">Video Poker</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="<?= Url::toRoute('home/login')?>"> Log In <span class="sr-only">(current)</span></a></li>
                <li><a href="<?= Url::toRoute('home/register')?>"> Register <span class="sr-only">(current)</span></a></li>
                <li><a href="<?= Url::toRoute('home/top10')?>"> Top 10 <span class="sr-only">(current)</span></a></li>


            </ul>

            <ul class="nav navbar-nav navbar-right">


                <ul class="nav navbar-nav">

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">User
                            <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Settings</a></li>
                            <li><a href="#">statistics</a></li>
                            <li><a href="#">Log Out</a></li>
                        </ul>
                    </li>

                </ul>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
</body>
