<?php
use ArmoredCore\Controllers\BaseController;
use ArmoredCore\WebObjects\Redirect;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\View;
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('header'); ?>

    <!-- container -->
    <div class="container">


        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Settings</h1>
                </header>

                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h3 class="thin text-center"> USER </h3>
                            <hr>
                            <form action="<?php echo Url::toRoute('user/edit')?>" method="post">
                                <p class="text-center">Click below to edit your account information:</p>
                                <div class="col-lg-7 text-right" >
                                    <button class="btn btn-action" type="submit"  background-color="red">Edit</button>
                                </div>

                            </form>

                            <br> </br>
                            <br> </br>
                            <form action="<?php echo Url::toRoute('user/statistics')?>" method="post">
                                <p class="text-center">Click below to check  your statistics:</p>

                                <div class=" text-center" >
                                    <button class="btn btn-action" type="submit"  background-color="red">Statistics</button>
                                </div>

                            </form>
                        </div>
                    </div>

                </div>

            </article>
            <!-- /Article -->

        </div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>