<?php
use ArmoredCore\Controllers\BaseController;
use ArmoredCore\WebObjects\Redirect;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\View;
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('header'); ?>

    <!-- container -->
    <div class="container">


        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">


                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <html>
                    <head>
                        <style>

                            table td {
                                border-left: 1px solid black;
                                border-right:1px solid black;
                                text-align :center ;


                            }
                            table th {
                                border: 1px solid black;
                                text-align :center ;

                            }
                            table{
                                border:1px solid black;
                            }
                        </style>
                    </head>
                    <body>

                    <table style="width:90%">
                        <tr>
                            <th>Prizes</th>
                            <th>Bet 1</th>
                            <th>Bet 2</th>
                            <th>Bet 3</th>
                            <th>Bet 4</th>
                            <th>Bet 5</th>

                        </tr>
                        <tr>
                            <td>Royal Flush .............</td>
                            <td bgcolor="#d3d3d3">250</td>
                            <td>500</td>
                            <td>750</td>
                            <td>1000</td>
                            <td>4000</td>



                        </tr>
                        <tr>
                            <td>Straight Flush ..........</td>
                            <td bgcolor="#d3d3d3">50</td>
                            <td>100</td>
                            <td>150</td>
                            <td>200</td>
                            <td>250</td>

                        </tr>
                        <tr>
                            <td>Four of a Kind .........</td>
                            <td bgcolor="#d3d3d3">25</td>
                            <td>50</td>
                            <td>75</td>
                            <td>100</td>
                            <td>125</td>
                        </tr>
                        <tr>
                            <td>Full House ..............</td>
                            <td bgcolor="#d3d3d3">9</td>
                            <td>18</td>
                            <td>27</td>
                            <td>36</td>
                            <td>45</td>
                        </tr>
                        <tr>
                            <td>Flush ......................</td>
                            <td bgcolor="#d3d3d3">6</td>
                            <td>12</td>
                            <td>18</td>
                            <td>24</td>
                            <td>30</td>
                        </tr>
                        <tr>
                            <td>Straight ...................</td>
                            <td bgcolor="#d3d3d3">4</td>
                            <td>8</td>
                            <td>12</td>
                            <td>16</td>
                            <td>20</td>
                        </tr>
                        <tr>
                            <td>Three of a Kind........</td>
                            <td bgcolor="#d3d3d3">3</td>
                            <td>6</td>
                            <td>9</td>
                            <td>12</td>
                            <td>15</td>
                        </tr>
                        <tr>
                            <td>Two Pair .................</td>
                            <td bgcolor="#d3d3d3">2</td>
                            <td>4</td>
                            <td>6</td>
                            <td>8</td>
                            <td>10</td>
                        </tr>
                        <tr>
                            <td>Jacks or Better .......</td>
                            <td bgcolor="#d3d3d3">1</td>
                            <td>2</td>
                            <td>3</td>
                            <td>4</td>
                            <td>5</td>
                        </tr>
                    </table>

                    </body>
                    </html>



                </div>

            </article>
            <!-- /Article -->

        </div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>