<?php

use ArmoredCore\Controllers\BaseController;
use ArmoredCore\WebObjects\Redirect;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\View;
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('header'); ?>

    <!-- container -->
    <div class="container">


        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">


                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <html>
                    <head>
                        <style>
                            <?php if ($_POST['bet'] == "1" ){ ?>
                            table td.classone {
                                background-color: grey;
                            }
                            <?php } else{ if ($_POST['bet'] == "2" ){ ?>

                            table td.classtwo{
                                background-color:grey ;
                            }

                            <?php } else{ if($_POST['bet'] == "3" ){?>
                                       table td.classthree{
                                background-color:grey ;
                            }

                            <?php } else{ if ($_POST['bet'] == "4" ){ ?>
                            table td.classfour {
                                background-color: grey;
                            }

                            <?php } else{ if ($_POST['bet'] == "5" ){   ?>

                                table td.classfive {
                                    background-color: grey;
                                }

                            <?php }}}}}?>



                            table td {
                                border-left: 1px solid black;
                                border-right:1px solid black;
                                text-align :center ;
                            }



                            table th {
                                border: 1px solid black;
                                text-align :center ;
                            }

                            table{
                                border:1px solid black;
                            }
                        </style>
                    </head>
                    <body>

                    <table style="width:90%">
                        <tg >
                            <th>Prizes</th>
                            <th>Bet 1</th>
                            <th>Bet 2</th>
                            <th>Bet 3</th>
                            <th>Bet 4</th>
                            <th>Bet 5</th>

                        </tg>
                        <tr>
                            <td >Royal Flush .............</td>
                            <td class="classone" >250</td>
                            <td class="classtwo">500</td>
                            <td class="classthree">750</td>
                            <td class="classfour">1000</td>
                            <td class="classfive">4000</td>



                        </tr>
                        <tr>
                            <td>Straight Flush ..........</td>
                            <td class="classone">50</td>
                            <td class="classtwo">100</td>
                            <td class="classthree">150</td>
                            <td class="classfour">200</td>
                            <td class="classfive">250</td>

                        </tr>
                        <tr>
                            <td>Four of a Kind .........</td>
                            <td class="classone">25</td>
                            <td class="classtwo">50</td>
                            <td class="classthree">75</td>
                            <td class="classfour">100</td>
                            <td class="classfive">125</td>
                        </tr>
                        <tr>
                            <td>Full House ..............</td>
                            <td class="classone">9</td>
                            <td class="classtwo">18</td>
                            <td class="classthree">27</td>
                            <td class="classfour">36</td>
                            <td class="classfive">45</td>
                        </tr>
                        <tr>
                            <td>Flush ......................</td>
                            <td class="classone">6</td>
                            <td class="classtwo">12</td>
                            <td class="classthree">18</td>
                            <td class="classfour">24</td>
                            <td class="classfive">30</td>
                        </tr>
                        <tr>
                            <td>Straight ...................</td>
                            <td class="classone">4</td>
                            <td class="classtwo">8</td>
                            <td class="classthree">12</td>
                            <td class="classfour">16</td>
                            <td class="classfive">20</td>
                        </tr>
                        <tr>
                            <td>Three of a Kind........</td>
                            <td class="classone">3</td>
                            <td class="classtwo">6</td>
                            <td class="classthree">9</td>
                            <td class="classfour">12</td>
                            <td class="classfive">15</td>
                        </tr>
                        <tr>
                            <td>Two Pair .................</td>
                            <td class="classone">2</td>
                            <td class="classtwo">4</td>
                            <td class="classthree">6</td>
                            <td class="classfour">8</td>
                            <td class="classfive">10</td>
                        </tr>
                        <tr>
                            <td>Jacks or Better .......</td>
                            <td class="classone">1</td>
                            <td class="classtwo">2</td>
                            <td class="classthree">3</td>
                            <td class="classfour">4</td>
                            <td class="classfive">5</td>
                        </tr>
                    </table>
                    <br>



                    </body>
                    </html>



                </div>

            </article>
            <!-- /Article -->

        </div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>